adding nojekyll file

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -3,21 +3,25 @@ name: Deploy to GitHub Pages
 on:
   push:
     branches: ['main']
-
+    
 jobs:
   build-and-deploy:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
-      - uses: actions/setup-node@v3
+      - uses: actions/checkout@v2
+      - uses: actions/setup-node@v2
         with:
           node-version: '18'
       - run: npm ci
       - run: npm run build
-      - name: Debug Build Directory
-        run: ls -la ./build
       - name: Create .nojekyll file
-        run: touch ./build/.nojekyll
+        run: |
+          if [ -d "build" ]; then
+            touch build/.nojekyll
+          else
+            echo "Build directory not found"
+            exit 1
+          fi
       - name: Deploy
         uses: peaceiris/actions-gh-pages@v3
         with:
